### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by SaaStudio** [gusthavosouza/SRTParser#2]
Please, fix the readme description. 
You write: "ArrayList<Subtitle> subtitles = **SRTReader**.getSubtitlesFromFile(path, keepNewLinesEscaped);"
correct "ArrayList<Subtitle> subtitles = **SRTParser**.getSubtitlesFromFile(path, keepNewLinesEscaped);"

**Comment by gusthavosouza** [comment]
@SaaStudio I am gonna write a better README file, and will be soon adding some more instructions in my website.
